name: Create Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  call-validation:
    uses: ./.github/workflows/validate.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'
      - name: Build
        run: |
          mvn -B org.apache.nifi:nifi-nar-maven-plugin:nar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/pulsar-timeplus-sink-*.nar
